POST http://127.0.0.1:5000/auth
content-type: application/json

{
    "username": "alejandroAdmin",
    "password": "Admin123"
}

### get pacientes
GET http://127.0.0.1:5000/pacientes/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDE4MzE5NTQsImV4cCI6MTcwMjQzNjc1NCwiaWQiOjIsInVzZXJuYW1lIjoiYWxlamFuZHJvQWRtaW4iLCJmdWxsbmFtZSI6IkphdmllciBBbGVqYW5kcm8gTG9wZXogUmFtaXJleiIsInJvbGVzIjpbIkFkbWluaXN0cmFkb3IiLCJFZGl0b3IiXX0.tGGHl1w81OHHSxTdZGXgbz1fpqf_tUMuPArO8G6iDMM


### get pacientes
POST http://127.0.0.1:5000/pacientes/guardar
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDA1MzE5MTQsImV4cCI6MTcwMTEzNjcxNCwidXNlcm5hbWUiOiJhbGVqYW5kcm9BZG1pbiIsImZ1bGxuYW1lIjoiSmF2aWVyIEFsZWphbmRybyBMb3BleiBSYW1pcmV6Iiwicm9sZXMiOlsiQWRtaW5pc3RyYXRvciIsIkVkaXRvciJdfQ.qQ036SH8-73JFNcTJRf953b3y_xYX9wUMxNk1PxPVSE

{"nombre":"Javier Lopez","numeroRegistro":"12345669","genId":"1","edad":"30","direccion":"Final Av simon bolivar","depId":"1","munId":"1","estadoCivil":"1","telefono":"70954803","fechaNacimiento":"1992-12-04","numeroDui":"0484748494","id_usuario":2}
### get pacientes
POST http://127.0.0.1:5000/pacientes/buscar
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDA1MzE5MTQsImV4cCI6MTcwMTEzNjcxNCwidXNlcm5hbWUiOiJhbGVqYW5kcm9BZG1pbiIsImZ1bGxuYW1lIjoiSmF2aWVyIEFsZWphbmRybyBMb3BleiBSYW1pcmV6Iiwicm9sZXMiOlsiQWRtaW5pc3RyYXRvciIsIkVkaXRvciJdfQ.qQ036SH8-73JFNcTJRf953b3y_xYX9wUMxNk1PxPVSE

{
    "busqueda": "Javier"
}

### get pacientes
PUT http://127.0.0.1:5000/pacientes/editar
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDAxMDMyNTQsImV4cCI6MTcwMDEwNjg1NCwidXNlcm5hbWUiOiJhbGVqYW5kcm9BZG1pbiIsImZ1bGxuYW1lIjoiSmF2aWVyIEFsZWphbmRybyBMb3BleiBSYW1pcmV6Iiwicm9sZXMiOlsiQWRtaW5pc3RyYXRvciIsIkVkaXRvciJdfQ.NBT7oataCzaN-Ye_VzpzCWpuGCRcguJCO3qHW81__1E

{
    "pacienteId": 16792,
    "nombre": "Juan Manuel Perez",
    "numero_registro": "161029022",
    "gen_id": 1,
    "edad": 34,
    "direccion": "Calle Principal Barrio el Centro",
    "dep_id": 1,
    "mun_id": 1,
    "estado_civil": 1,
    "telefono": "7890-3033",
    "fecha_nacimiento": "1988-01-01",
    "numero_dui": "04221133-2",
    "nombre_madre": "",
    "nombre_padre": "",
    "responsable": "",
    "tel_contacto": "",
    "id_usuario_modifica": 1
}

### borrar pacientes
DELETE  http://127.0.0.1:5000/pacientes/borrar/16781
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDA1MzE5MTQsImV4cCI6MTcwMTEzNjcxNCwidXNlcm5hbWUiOiJhbGVqYW5kcm9BZG1pbiIsImZ1bGxuYW1lIjoiSmF2aWVyIEFsZWphbmRybyBMb3BleiBSYW1pcmV6Iiwicm9sZXMiOlsiQWRtaW5pc3RyYXRvciIsIkVkaXRvciJdfQ.qQ036SH8-73JFNcTJRf953b3y_xYX9wUMxNk1PxPVSE
